name: first-action
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: printing greetings
        run: echo "hello world!"
      - name: printing bye
        run: echo "good bye"
